#!/bin/sh
# Statusbar loop
while true; do DATE=$(date +'%Y-%m-%d %R')
   VOLUME=$(pacmd list-sinks | grep -A 15 '* index' | awk '/volume: front/{ print $5 }' | sed 's/[%|,]//g') 

   xsetroot -name "$DATE | $VOLUME%"
   sleep 1
done &

########################################################################
##  Merge in defaults and keymaps                                     ##
########################################################################

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    /usr/bin/xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    /usr/bin/xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
    /usr/bin/xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
    /usr/bin/xmodmap $usermodmap
fi

# Start fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

# Start syncthing
syncthing serve --no-browser --no-restart --logflags=0 &

# Choose desktop wallpaper
feh --bg-scale $HOME/Pictures/Music/Rella/1680x1050/Symphony_1680x1050.jpg

# Start other programs
pulseaudio --start &
picom &
conky &
lxqt-notificationd &
fcitx &
xscreensaver -no-splash &
nm-applet &

# Start dwm
exec dbus-launch --exit-with-session dwm
