set backupdir=~/.vim/backup//
set directory=~/.vim/backup//
set undodir=~/.vim/backup//
set guifont=Monospace\ 12
set number
set tabstop=4
set shiftwidth=4

" Use space characters instead of tabs.
set expandtab

" enable syntax
syntax enable

" breezy color scheme (for vim terminal)
" https://github.com/fneu/breezy

" seoulbones color scheme (for gvim)
" Use google_dark as the airline theme
" https://github.com/zenbones-theme/zenbones.nvim/blob/main/colors/seoulbones.vim
" https://github.com/vim-airline/vim-airline-themes/blob/master/autoload/airline/themes/google_dark.vim

if has('gui_running')
  colorscheme seoulbones
  let g:airline_theme='google_dark'
else
  colorscheme breezy
  set termguicolors "
  set background=light
  let g:airline_theme='breezy'
endif

" make airline use powerline fonts (which provide fancy arrow symbols)
let g:airline_powerline_fonts=1
