set backupdir=~/.vim/backup//
set directory=~/.vim/backup//
set undodir=~/.vim/backup//
set guifont=Monospace\ 12
set number
set tabstop=4
set shiftwidth=4

" Use space characters instead of tabs.
set expandtab

" Use the breezy theme in vim terminal. Use the PaperColor theme in gvim.
" https://github.com/fneu/breezy 
" https://github.com/NLKNguyen/papercolor-theme/
" https://github.com/vim-airline/vim-airline-themes/blob/master/autoload/airline/themes/papercolor.vim
if has('gui_running')
  syntax enable
  set t_Co=256
  colorscheme PaperColor
  set background=light
  let g:airline_theme='papercolor'
else
  colorscheme breezy
  set termguicolors "
  set background=light
  let g:airline_theme='breezy'
endif

" make airline use powerline fonts (which provide fancy arrow symbols)
let g:airline_powerline_fonts=1
